### ISSUE TITLE
Nvim-Tree problems

### ISSUE THREAD

**Issue by ghost** [anurag3301/my-linux-setup#4]
When configuring the neovim config, it shows this error.  
![300322121843](https://user-images.githubusercontent.com/93096206/160893867-09d831ef-6f10-4dc6-9bd4-8f18566f996a.png)
How would I go about fixing this.  Thanks again

**Comment by anurag3301** [comment]
I have fixed it but it's not working, there is an issue going on you can go through it. [Issue#1094](https://github.com/kyazdani42/nvim-tree.lua/issues/1094)

**Comment by ghost** [comment]
it's making my brain hurt

**Comment by gokberkgunes** [comment]
Hello, I have left a comment which explains how to fix the issue [here](https://github.com/kyazdani42/nvim-tree.lua/issues/1094#issuecomment-1100473519). Please take a look at it.

**Comment by anurag3301** [comment]
Thanks @gokberkgunes, this issue was long due.
