### ISSUE TITLE
Hide extra text on top of the prompt while using runner.lua

### ISSUE THREAD

**Issue by RameshKumarGogoi** [anurag3301/my-linux-setup#6]
I pasted the codes related to runner.lua to my config file but it shows some extra text at the top of the prompt. How to hide it ?
```lua
local run_command_table = {
  ['cpp'] = 'g++ % -o %:r && ./%:r',
  ['c'] = 'gcc % -o %:r && ./%:r',
  ['python'] = 'python %',
  ['lua'] = 'lua %',
  ['java'] = 'javac % && java %:r',
  ['zsh'] = 'zsh %',
  ['sh'] = 'sh %',
  ['rust'] = 'rustc % && ./%:r',
  ['go'] = 'go run %',
  ['javascript'] = 'node %'
}

local extra = 'echo \"\\\\n\\\\033[0;33mPlease Press ENTER to continue \\\\033[0m\"; read; exit;'

function run_code()
  if (run_command_table[vim.bo.filetype]) then
    vim.cmd("2TermExec cmd='" .. run_command_table[vim.bo.filetype] .. "; " .. extra .. "' direction=float")
  else
    print("\nFileType not supported\n")
  end
end

-- Use the following function to update the execution command of a filetype temporarly
-- Usage :lua update_command_table(filetype) --OR-- :RunUpdate filetype
-- Example :RunUpdate python
function update_command_table(filetype)
  local command

  if (run_command_table[filetype]) then
    command = vim.fn.input(string.format("Update run command of filetype (%s): ", filetype),
      run_command_table[filetype], 'file')
  else
    command = vim.fn.input(string.format("Add new run command of filetype (%s): ", filetype))
  end

  if (#command ~= 0) then
    run_command_table[filetype] = command
    print("  Updated!")
  end
end

vim.cmd('command! Run :lua run_code()')

vim.cmd('command! -nargs=1 RunUpdate :lua update_command_table(<f-args>)')

vim.api.nvim_set_keymap('n', '<F5>', ':Run<CR>', { noremap = true, silent = true })
```

```sh
g++ hw.cpp -o hw && ./hw; echo "\n\033[0;33mPlease Press ENTER to continue \033[0m"; read; exit;
➜  ~ g++ hw.cpp -o hw && ./hw; echo "\n\033[0;33mPlease Press ENTER to continue \033[0m"; read; exit;

```

**Comment by anurag3301** [comment]
@expacc007 are you talking about the extra ` echo "\n\033[0;33mPlease Press ENTER to continue \033[0m"; read; exit;` is responsible for this
![image](https://user-images.githubusercontent.com/52702259/168946087-cc8a08fe-c4ac-4be6-b8bc-415911d80d93.png)
I added this cuz I wanted the terminal to exit after the execution of the code.
If you don't like this you can just set `local extra = ''`. But you'll lose it and be dropped to the next shell prompt after executing your code.

**Comment by anurag3301** [comment]
oh if you are talking about the extra text on top of the prompt
![image](https://user-images.githubusercontent.com/52702259/168947016-44d32388-3e88-426c-b833-75064a0d83ac.png)
It must be something to do with toggleterm, ill fix this soon.

**Comment by RameshKumarGogoi** [comment]
> oh if you are talking about the extra text on top of the prompt ![image](https://user-images.githubusercontent.com/52702259/168947016-44d32388-3e88-426c-b833-75064a0d83ac.png) It must be something to do with toggleterm, ill fix this soon.

Let me know what changes you made to fix this.
Also, thanks for making this! I was looking for a code runner.

**Comment by anurag3301** [comment]
Hey @expacc007 I have created an issue in ToggleTerm https://github.com/akinsho/toggleterm.nvim/issues/226 
hopefully gets fixed soon, I'll let you know if it gets fixed.

**Comment by anurag3301** [comment]
A pretty long-due issue, finally got time to fix it. Using the method of terminal creation mentioned in this issue 
https://github.com/akinsho/toggleterm.nvim/issues/226#issuecomment-1145160357

No more extra text at the top.
![image](https://user-images.githubusercontent.com/52702259/210723696-da13a405-3247-4719-aa24-aa1ebfea7d62.png)

**Comment by anurag3301** [comment]
Hey @RameshKumarGogoi if you are still here, try it out
