### ISSUE TITLE
Dashboard config not loading correctly

### ISSUE THREAD

**Issue by tqwewe** [anurag3301/my-linux-setup#8]
Hi, I've just installed your nvim configs and run `PackerClean`, `PackerInstall`, and `PackerSync`.

Though the dashboard seems to be default with the config not being loaded.

![Screenshot_20220728_153400](https://user-images.githubusercontent.com/16362377/181432140-c7279012-0c2d-4bd6-b9d0-b00ebb9359e9.png)

When I run `:lua print(vim.g.dashboard_default_executive)`, it prints `telescope`. And `:lua print(vim.g.dashboard_custom_header[2])` seems to also be correct, so I'm not sure why the dashboard might not be using these settings, any ideas?

**Comment by anurag3301** [comment]
Hey @tqwewe thanks for letting me know, there are some changes made to [glepnir/dashboard-nvim](https://github.com/glepnir/dashboard-nvim) plugin, I just pulled the latest commits and have the same output, I'm fixing it. Ill let you know when it's done.

**Comment by anurag3301** [comment]
@tqwewe I have made the required changes, try it out and let me know if it works for you or not.
